### PR TITLE
Setup Github Issue Templates

### PR DESCRIPTION
**Pull request by JasonLandbridge**
I basically imported these from my own project: https://github.com/PlexRipper/PlexRipper/issues

I changed some options around to reflect Nuxt-Quasar. Please check: https://github.com/JasonLandbridge/nuxt-quasar/issues/new/choose to see how this looks in action

Let me know if you like this and/or would like to change anything.

### CODE REVIEW

**Comment by Maiquu** [comment]
Thanks you! These are great! :smiley:

**Comment by Maiquu** [comment]
I merged right away but do you think the type of browser would be necessary? Since browser related issues would most likely be in quasar's domain.

**Comment by JasonLandbridge** [comment]
Thanks for the merge! Yeah I figured that it can't hurt to ask, I've had some browser specific issues in the past with certain libraries I used and it helped narrow down the solution when I knew in which browser it happend.

**Comment by Maiquu** [comment]
Nuxt provides a command that output user environment details. Nuxt [issue template](https://github.com/nuxt/nuxt/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) asks for the output of said command. That would give quite a bit of info except the quasar version. 

I will most likely add it to our template but I wanted to ask for your opinion.

**Comment by JasonLandbridge** [comment]
Not at all, it's a small thing for a bug reporter and te more info the better. 
Example when I run it:
```bash
RootDir: /mnt/PROJECTS/PlexRipper/src/WebAPI/ClientAppV2                                                                                                                                                                                                                                                      09:28:02
Nuxt project info:                                                                                                                                                                                                                                                                                            09:28:02

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `ssr`, `srcDir`, `devServer`, `runtimeConfig`, `modules`, `quasar`, `typescript`, `macros`, `i18n`, `alias`, `components`, `vite`, `telemetry`
- Runtime Modules:  `nuxt-quasar-ui@1.0.5`, `@vueuse/nuxt@9.13.0`, `@nuxt/devtools@0.2.5`, `@nuxtjs/i18n@8.0.0-beta.10`, `@vue-macros/nuxt@1.2.3`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                                                                                                                                                   09:28:02

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com


```

**Pull request merged**
