### PR TITLE
Added composable to set the Quasar default values through a Nuxt plugin

### PR DESCRIPTION
**Pull request by JasonLandbridge**
This implements: #35 

This is how the PlayGround looks:

image

### CODE REVIEW

**Comment by JasonLandbridge** [comment]
Screenshot above has a type, fixed it

**Comment by Maiquu** [comment]
It's not working correctly after I fixed the hydration warning at playground `q-markup-table`. It seems that defaults are not being applied when components are rendered on server side.

**Comment by JasonLandbridge** [comment]
That's a shame, I can only confirm that it works at least in SPA mode without the SSR. It can be a non-ssr feature maybe?
I honestly have no experience with SSR, I always do SPA

**Comment by Maiquu** [comment]
I debugged `@vue/server-renderer`, server renderer seems to be receiving the non-modified versions of components.

Also after I thought about it, I think a function like this should not be part of this module. Because this function pretty much can be applied to any component from any other UI library.

Even if we reduce the scope of the function, I'm not if it will be possible given how SSR is handled.

**Comment by JasonLandbridge** [comment]
Ah I see, no problem :+1:

**Pull request closed without merging**
