### PR TITLE
Mute SASS/SCSS deprecation warnings due to Quasar

### PR DESCRIPTION
**Pull request by JasonLandbridge**
Hi there, 

There is this annoying issue where everytime Nuxt v3 is started in dev mode, or when updating any styling, the console is filled with these deprecation warnings coming from Quasar.

[Example](https://github.com/quasarframework/quasar/pull/15514)

Possible fixes were given here: [Stackoverflow](https://stackoverflow.com/questions/67812380/disable-dart-sass-warnings-produced-by-external-theme-file), however none work.

Unfortunately, Quasar is unwilling to fix this as shown by the many attempts by the community to fix this:

- https://github.com/quasarframework/quasar/pull/11877
- https://github.com/quasarframework/quasar/pull/12034
- https://github.com/quasarframework/quasar/pull/14213
- https://github.com/quasarframework/quasar/pull/14816

The main reason being: 
> This has been discussed many times. The "sass" package needs to be pinned to v1.32.12 otherwise, indeed some deprecation warnings will appear. However, it is not easy to convert to the new syntax without adding breaking changes to our developer's apps (a definitely no-go) -- hence the pinning of the "sass" package which should not be touched (manually installed) by our devs (supplied by Quasar CLI).

https://github.com/quasarframework/quasar/pull/14213#issuecomment-1219170007

However, @bompus found a smart workaround here: https://github.com/quasarframework/quasar/pull/12034#issuecomment-1021503176

So I have taken his gist and inserted this into Nuxt-Quasar, toggle-able under an option but is enabled by default, since these specific deprecation warnings are useless for the end-user. 

I have also ensured that any config that is added by the user, is preserved and loaded after this fix. 
Example of how this would look like:
```ts
vite: {
    css: {
        preprocessorOptions: {
            scss: {
                ...silenceSomeSassDeprecationWarnings,
                additionalData: '@use "@/assets/scss/_variables.scss" as *;',
            },
            sass: {
                ...silenceSomeSassDeprecationWarnings,
            },
        },
    },
},
```

### CODE REVIEW

**Comment by Maiquu** [comment]
Is it safe to use non-pinned version of sass with quasar? I don't know much about sass so I can't tell if it would break things in the long term.

**Comment by JasonLandbridge** [comment]
I think it is, Quasar has that version pinned in their `package.json` and in my own `package.json` I have the following as well without problems:

```json
{
	"devDependencies": {
		"nuxt": "^3.3.1",
		"nuxt-quasar-ui": "^1.0.5",
		"sass": "^1.59.3",
		"sass-loader": "^13.2.0",
	}
}
```

So my guess is that my own custom styling in my project the `"sass": "^1.59.3"` is used, and for the Quasar styling their pinned version is used

**Comment by JasonLandbridge** [comment]
Rebased [QuasarSassMuteDeprecationWarnings](https://github.com/JasonLandbridge/nuxt-quasar/tree/QuasarSassMuteDeprecationWarnings) to main to resolve conflicts

**Comment by Maiquu** [comment]
I modified the code a bit. Added type safety for the quasar modules. Bumped the sass version since we don't enforce pinning the sass version. (Which would also allow us to test the new feature)

Removed some of the checks performed in function since when we setup the GitHub workflows, there shouldn't be any need to runtime checks for internal methods.

Would be glad if you could also skim the changes and tell if you see any issues with it.

**Comment by JasonLandbridge** [comment]
Yeah great changes! Thanks! It seems I've worked too long with old javascript versions at companies that I forgot there are more cleaner ways of writing things, so greatly appreciated!

**Review by Maiquu — APPROVED** [review]

**Pull request merged**
